# -----------------------------
# TLS Certificate (cert-manager)
# -----------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-travelersources-com
  namespace: istio-ingress  ## gateway ns 
spec:
  secretName: tls-travelersources-com
  dnsNames:
    - travelersources.com
  issuerRef:
    name: production-cluster-issuer-http
    kind: ClusterIssuer